In [5]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [6]:
df=pd.read_csv("homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [7]:
model=linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [8]:
model.coef_

array([135.78767123])

In [9]:
model.intercept_

180616.43835616432

In [10]:
import pickle

In [11]:
with open('model_pickle','wb') as f:
    pickle.dump(model,f)

In [12]:
with open('model_pickle','rb') as f:
    mp=pickle.load(f)

In [13]:

mp.predict(np.array([[5000]]))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [14]:
import joblib

In [15]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [16]:
mj=joblib.load('model_joblib')

In [17]:
mj.predict(np.array([[5000]]))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [18]:
mj.coef_

array([135.78767123])

In [19]:
mj.intercept_

180616.43835616432